### ISSUE TITLE
instanciating a Resource() directly 

### ISSUE THREAD

**Issue by django-rdf-tools** [cburgmer/surf#1]
On the last version of the "surf" branch , SuRF-1.1.4_r352-py2.7
OK, perhaps I'm doing it all wrong...
Trying to catch a dc:title attached to the "root node" of a simple rdf file
I followed the doc : "Initialize a Resource, with the subject (a URI - either a string or a URIRef)."

```
import surf,rdflib
store = surf.Store(reader='rdflib',writer='rdflib',rdflib_store='IOMemory',auto_load=True)
session = surf.Session(store)
store.load_triples(source='http://www.w3.org/2003/01/geo/wgs84_pos#')
test = surf.resource.Resource(subject=rdflib.URIRef('http://www.w3.org/2003/01/geo/wgs84_pos#'))
```

...but here :

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/dom/django/.virtualenvs/base/lib/python2.7/site-packages/SuRF-1.1.4_r352-py2.7.egg/surf/resource/__init__.py", line 187, in __init__
    elif self.session and self.store_key:
  File "/Users/dom/django/.virtualenvs/base/lib/python2.7/site-packages/SuRF-1.1.4_r352-py2.7.egg/surf/resource/__init__.py", line 463, in __getattr__
    raise AttributeError('Not a predicate: %s' % attr_name)
AttributeError: Not a predicate: session
```

Ok, then I modified the source and dared returning an empty list (   # an empty list ? hmmm --- error :]  ) but it breaks everything:

```
session.get_class(test)
TypeError: 'list' object is not callable

session.get_resource(rdflib.URIRef('http://www.w3.org/2003/01/geo/wgs84_pos#'))
AttributeError: 'NoneType' object has no attribute 'store_key'
```

**Comment by cburgmer** [comment]
Hi Dominique, there a some things here:

First, you are loading an onthology into SuRF for which it was not designed. For example 'http://www.w3.org/2003/01/geo/wgs84_pos#' has no Class information, the basic foundation of SuRF's class mapping. As far as I can see the whole document only includes RDFS description about the classes and its properties. However SuRF is designed to work on instance data.

However I believe you have found a bug. You call session.get_resource() without passing it a Class. While it seems SuRF was designed to handle this (the code has been written before I used SuRF) it is currently broken. I'm creating a bug report at the project page, check there if you want to know about any possible solution.

I think it would be best if we would further discuss issues like that one mailing list. It was made for answering questions and who says they wouldn't be interested in the issues you came up with. Right now it's only me who can answer here and for the bug above, it's Cosmin who probably knows most about that.

But keep it coming, good to see you are digging deep :) I'll close this issue here for now, the bug is going upstream.

**Comment by cburgmer** [comment]
I wasn't too clear on that, so:

What you want to do here:

> > > test = surf.resource.Resource(subject=rdflib.URIRef('http://www.w3.org/2003/01/geo/wgs84_pos#'))
> > > is normally done via
> > > test = session.get_resource(rdflib.URIRef('http://www.w3.org/2003/01/geo/wgs84_pos#'))

or, if you know the class:

> > > MyClass = session.get_class(rdflib.URIRef('http://SOME URL'))
> > > test = MyClass('http://SOME OTHER URL')
